source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘7.0’

target "Daoting" do

pod 'AFNetworking', '~> 2.0'
pod 'StreamingKit', '~> 0.1'
pod 'LBBlurredImage'
pod 'TSMessages'
pod 'MarqueeLabel'
pod 'Shimmer'

end